version: '3'
services:
    php-fpm:
        build:
            context: "."
            dockerfile: "php-fpm/Dockerfile"
        volumes:
            - "./www:/var/www/html"
        expose:
            - "9000"
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./www:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        depends_on:
            - "php-fpm"
