services:
    postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "example"
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
            - "./postgresql.conf:/etc/postgresql/postgresql.conf"
            - "./postgres:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
    customer:
        image: "nginx:alpine"
        volumes:
            - "./customer/www:/var/www"
            - "./customer/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - "php-fpm"
    php-fpm:
        build:
            context: "."
            dockerfile: "php-fpm/Dockerfile"
        volumes:
            - "./www:/var/www/html"
        expose:
            - "9000"
        depends_on:
            - "postgres"
        environment:
            DATABASE_HOST: postgres
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./www:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        depends_on:
            - "php-fpm"
