services:
    postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "example"
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
            - "./postgresql.conf:/etc/postgresql/postgresql.conf"
            - "./postgres:/var/lib/postgresql/data"
    php-fpm:
        build:
            context: "."
            dockerfile: "php-fpm/Dockerfile"
        volumes:
            - "./www:/var/www/html"
        depends_on:
            - "postgres"
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./www:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "8000:80"
        depends_on:
            - "php-fpm"

