services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  web:
    build: ./myapp/
    command: bash -c "bundle exec rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./myapp:/myapp
    ports:
      - "8016:3000"
    links:
      - db
